// code generated by jonson-generate; DO NOT EDIT.
		
package account

import (
	"github.com/doejon/jonson"
)


// systems/account/account.go:20 -- MeV1
func MeV1(ctx *jonson.Context) (*MeV1Result, error) {
	v, err := ctx.CallMethod("account/me.v1", nil, nil)
	if err != nil {
		return nil, err
	}
	if v != nil {
		return v.(*MeV1Result), nil
	}
	return nil, nil
}

// systems/account/account.go:36 -- GetProfileV1
func GetProfileV1(ctx *jonson.Context, p *GetProfileV1Params) (*GetProfileV1Result, error) {
	v, err := ctx.CallMethod("account/get-profile.v1", p, nil)
	if err != nil {
		return nil, err
	}
	if v != nil {
		return v.(*GetProfileV1Result), nil
	}
	return nil, nil
}
