// code generated by jonson-generate; DO NOT EDIT.
		
package account

import (
	"github.com/doejon/jonson"
)


// account.go -- MeV1
func MeV1(ctx *jonson.Context) (*MeV1Result, error) {
	v, err := ctx.CallMethod("account/me.v1", jonson.RpcHttpMethodGet, nil)
	if err != nil {
		return nil, err
	}
	if v != nil {
		return v.(*MeV1Result), nil
	}
	return nil, nil
}

// account.go -- GetProfileV1
func GetProfileV1(ctx *jonson.Context, p *GetProfileV1Params) (*GetProfileV1Result, error) {
	v, err := ctx.CallMethod("account/get-profile.v1", jonson.RpcHttpMethodPost, p)
	if err != nil {
		return nil, err
	}
	if v != nil {
		return v.(*GetProfileV1Result), nil
	}
	return nil, nil
}

// account.go -- ProcessV1
func ProcessV1(ctx *jonson.Context) error {
	_, err := ctx.CallMethod("account/process.v1", jonson.RpcHttpMethodGet, nil)
	if err != nil {
		return err
	}
	
	return nil
}
