// code generated by jonson-generate; DO NOT EDIT.
		
package account

import (
	"reflect"
"github.com/doejon/jonson"
)


// provider.authorization.go:6 -- Private -- struct
var TypePrivate = reflect.TypeFor[**Private]()

func RequirePrivate(ctx *jonson.Context) *Private {
	if v := ctx.Require(TypePrivate).(*Private); v != nil {
		return v
	}
	return nil
}

// provider.authorization.go:14 -- Public -- struct
var TypePublic = reflect.TypeFor[**Public]()

func RequirePublic(ctx *jonson.Context) *Public {
	if v := ctx.Require(TypePublic).(*Public); v != nil {
		return v
	}
	return nil
}
